#!/usr/bin/env python3
"""htmlgen.py — render an :class:`~api_docs.introspect.Index` to a static site.

The output is a self-contained directory (no external assets, no build step, no
JavaScript framework) suitable for publishing straight to GitHub Pages:

  index.html        landing page: packages -> modules, with a client-side filter
  <module>.html     one page per module, listing classes, methods, functions
  search.json       flat symbol table powering the filter box and agent tooling
  apidocs.css       embedded-free stylesheet (one file, no CDN)

Because it is fed by the AST core, generating the site never imports the
documented code — the same reason the MCP server can run anywhere. ``build_site``
is the single entry point.
"""
from __future__ import annotations

import html
import json
from pathlib import Path

from .introspect import Index, Klass, Module, build_index, summary

_CSS = """\
:root { --fg:#1b1f24; --muted:#57606a; --bg:#fff; --card:#f6f8fa; --accent:#0969da;
        --border:#d0d7de; --mono:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; }
@media (prefers-color-scheme: dark) {
  :root { --fg:#e6edf3; --muted:#8b949e; --bg:#0d1117; --card:#161b22;
          --accent:#58a6ff; --border:#30363d; } }
* { box-sizing: border-box; }
body { font: 15px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif;
       color: var(--fg); background: var(--bg); margin: 0; }
.wrap { max-width: 960px; margin: 0 auto; padding: 1.5rem 1.25rem 4rem; }
header { border-bottom: 1px solid var(--border); margin-bottom: 1.5rem; }
h1 { font-size: 1.6rem; margin: .2rem 0; }
h2 { font-size: 1.2rem; margin: 2rem 0 .5rem; border-bottom: 1px solid var(--border); padding-bottom: .3rem; }
h3 { font-size: 1rem; margin: 1.4rem 0 .3rem; }
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
.muted { color: var(--muted); }
code, .sig, pre { font-family: var(--mono); font-size: .86em; }
.sig { background: var(--card); border: 1px solid var(--border); border-radius: 6px;
       padding: .35rem .55rem; display: block; margin: .35rem 0 .2rem; overflow-x: auto; }
.doc { white-space: pre-wrap; color: var(--fg); margin: .2rem 0 1rem; }
.kind { font-size: .72rem; text-transform: uppercase; letter-spacing: .04em;
        color: var(--muted); border: 1px solid var(--border); border-radius: 999px;
        padding: .05rem .45rem; margin-left: .4rem; }
.modlist { list-style: none; padding: 0; }
.modlist li { padding: .15rem 0; }
input#filter { width: 100%; padding: .5rem .65rem; font-size: 1rem; border: 1px solid var(--border);
               border-radius: 8px; background: var(--card); color: var(--fg); margin: .5rem 0 1rem; }
.crumbs { font-size: .85rem; margin-bottom: 1rem; }
.member { border-left: 2px solid var(--border); padding-left: .8rem; margin: 1.1rem 0; }
.loc { font-size: .8rem; color: var(--muted); }
footer { margin-top: 3rem; font-size: .8rem; color: var(--muted); border-top: 1px solid var(--border); padding-top: 1rem; }
"""

_FILTER_JS = """\
const f=document.getElementById('filter');
if(f){f.addEventListener('input',()=>{const q=f.value.toLowerCase();
document.querySelectorAll('[data-name]').forEach(el=>{
el.style.display=el.dataset.name.includes(q)?'':'none';});});}
"""


def _esc(s: str) -> str:
    return html.escape(s or "")


def _page(title: str, body: str, *, depth: int = 0) -> str:
    root = "./"
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{_esc(title)}</title>
<link rel="stylesheet" href="{root}apidocs.css"></head>
<body><div class="wrap">{body}
<footer>Generated by <code>apidocs</code> — dispatch API reference.
Static, derived from source docstrings. <a href="{root}index.html">Index</a></footer>
</div><script src="{root}apidocs.js"></script></body></html>
"""


def _module_filename(qualname: str) -> str:
    return qualname.replace(".", "-") + ".html"


def _render_member_func(fn) -> str:
    tag = ' <span class="kind">property</span>' if getattr(fn, "is_property", False) else ""
    deco = ""
    if fn.decorators:
        deco = '<div class="loc">' + ", ".join("@" + _esc(d) for d in fn.decorators) + "</div>"
    doc = f'<div class="doc">{_esc(fn.docstring)}</div>' if fn.docstring else '<div class="doc muted">(no docstring)</div>'
    return (
        f'<div class="member" id="{_esc(fn.name)}" data-name="{_esc(fn.name.lower())}">'
        f'<h3>{_esc(fn.name)}<span class="kind">{_esc(fn.kind)}</span>{tag}</h3>'
        f'{deco}<code class="sig">{_esc(fn.signature())}</code>'
        f'{doc}<div class="loc">{_esc(fn.file)}:{fn.lineno}</div></div>'
    )


def _render_member_class(cls: Klass) -> str:
    bases = f"({_esc(', '.join(cls.bases))})" if cls.bases else ""
    doc = f'<div class="doc">{_esc(cls.docstring)}</div>' if cls.docstring else '<div class="doc muted">(no docstring)</div>'
    methods = "".join(_render_member_func(m) for m in cls.methods)
    inner = f'<div style="margin-left:1rem">{methods}</div>' if methods else ""
    return (
        f'<div class="member" id="{_esc(cls.name)}" data-name="{_esc(cls.name.lower())}">'
        f'<h3>class {_esc(cls.name)}{bases}<span class="kind">class</span></h3>'
        f'{doc}<div class="loc">{_esc(cls.file)}:{cls.lineno}</div>{inner}</div>'
    )


def _render_module_page(mod: Module) -> str:
    kind = "package" if mod.is_package else "module"
    body = [
        '<header><div class="crumbs"><a href="index.html">dispatch API</a> / '
        f"{_esc(mod.qualname)}</div>"
        f"<h1>{_esc(mod.qualname)}<span class=\"kind\">{kind}</span></h1></header>",
        f'<div class="doc">{_esc(mod.docstring)}</div>' if mod.docstring else "",
        '<input id="filter" placeholder="filter members in this module…" autocomplete="off">',
    ]
    if mod.classes:
        body.append("<h2>Classes</h2>")
        body.extend(_render_member_class(c) for c in mod.classes)
    if mod.functions:
        body.append("<h2>Functions</h2>")
        body.extend(_render_member_func(f) for f in mod.functions)
    if not mod.classes and not mod.functions:
        body.append('<p class="muted">No public classes or functions.</p>')
    return _page(f"{mod.qualname} — dispatch API", "\n".join(body))


def _render_index_page(index: Index) -> str:
    body = [
        "<header><h1>dispatch API reference</h1>"
        '<p class="muted">Auto-generated from source docstrings. '
        f"{len(index.modules)} modules across {len(index.packages())} packages.</p></header>",
        '<input id="filter" placeholder="filter modules…" autocomplete="off">',
    ]
    for pkg in index.packages():
        mods = [m for m in index.module_names() if m == pkg or m.startswith(pkg + ".")]
        body.append(f"<h2>{_esc(pkg)}</h2><ul class=\"modlist\">")
        for q in mods:
            mod = index.modules[q]
            body.append(
                f'<li data-name="{_esc(q.lower())}"><a href="{_module_filename(q)}">{_esc(q)}</a> '
                f'<span class="muted">— {_esc(summary(mod.docstring))}</span></li>'
            )
        body.append("</ul>")
    return _page("dispatch API reference", "\n".join(body))


def search_records(index: Index) -> list[dict]:
    """Flat symbol table: one record per documented symbol (the search index)."""
    out: list[dict] = []
    for q, mod in index.modules.items():
        page = _module_filename(q)
        out.append({"path": q, "kind": "package" if mod.is_package else "module",
                    "summary": summary(mod.docstring), "url": page, "file": mod.file})
        for fn in mod.functions:
            out.append({"path": fn.qualname, "kind": fn.kind, "summary": summary(fn.docstring),
                        "url": f"{page}#{fn.name}", "file": fn.file})
        for cls in mod.classes:
            out.append({"path": cls.qualname, "kind": "class", "summary": summary(cls.docstring),
                        "url": f"{page}#{cls.name}", "file": cls.file})
            for m in cls.methods:
                out.append({"path": m.qualname, "kind": m.kind, "summary": summary(m.docstring),
                            "url": f"{page}#{m.name}", "file": m.file})
    return out


def build_site(out_dir: str | Path, index: Index | None = None, **index_kwargs) -> Path:
    """Write the full static site to ``out_dir`` and return the path written.

    Builds an :class:`Index` if one is not supplied (passing through any
    ``build_index`` keyword arguments). Existing ``out_dir`` contents are left in
    place except for files this generator overwrites.
    """
    if index is None:
        index = build_index(**index_kwargs)
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "apidocs.css").write_text(_CSS, encoding="utf-8")
    (out / "apidocs.js").write_text(_FILTER_JS, encoding="utf-8")
    (out / "index.html").write_text(_render_index_page(index), encoding="utf-8")
    (out / "search.json").write_text(json.dumps(search_records(index), indent=1), encoding="utf-8")
    # GitHub Pages serves Jekyll by default, which drops files it considers
    # special; .nojekyll publishes the directory verbatim.
    (out / ".nojekyll").write_text("", encoding="utf-8")
    for q, mod in index.modules.items():
        (out / _module_filename(q)).write_text(_render_module_page(mod), encoding="utf-8")
    return out
